export {
	type AdjudicationDecision,
	type AdjudicationResult,
	type AdjudicationTemplate,
	adjudicationDecisionSchema,
	adjudicationTemplate,
	applyAdjudication,
} from "./adjudication";
export {
	ANCHOR_MAX_COUNT,
	type AnchorTableCell,
	anchorMap,
	type EvidenceAnchor,
	hasTableRows,
	isAnchorId,
	SENTIMENT_EVIDENCE_VERSION,
	segmentAnswer,
} from "./anchors";
export {
	decodeRunCursor,
	encodeRunCursor,
	type MentionBackfillCounts,
	type MentionBackfillResult,
	type RunCursor,
	runMentionBackfill,
	runSentimentEnqueue,
	type SentimentEnqueueInventory,
	type SentimentEnqueueResult,
} from "./backfill";
export {
	acquireProbe,
	BREAKER_OPENING_CLASSES,
	BREAKER_PROBE_LEASE_SECONDS,
	breakerBackoffMs,
	classifyDispatchFailure,
	type DispatchFailureClass,
	databaseNow,
	decideBreaker,
	listBlockingBreakers,
	listBreakers,
	openBreakerManually,
	type ProbeOutcome,
	readBreaker,
	resetBreaker,
} from "./breaker";
export {
	acceptCanaryRunId,
	evaluateSentimentCanary,
	inspectSentimentCanaryRun,
	inspectSentimentCanaryRunState,
	isPristineCanaryRun,
	parseSentimentCanaryContract,
	preflightSentimentCanary,
	runSentimentCanary,
	SENTIMENT_CANARY_DEADLINE_MS,
	SENTIMENT_CANARY_LIMITS,
	SENTIMENT_CANARY_REJECT_CODES,
	SENTIMENT_CANARY_WATCHDOG_MS,
	type SentimentCanaryContract,
	SentimentCanaryContractError,
	type SentimentCanaryEntity,
	SentimentCanaryError,
	SentimentCanaryInputDriftError,
	type SentimentCanaryOutcome,
	type SentimentCanaryReason,
	type SentimentCanaryRejectCode,
	type SentimentCanaryReport,
	type SentimentCanaryRunDescription,
	type SentimentCanaryRunState,
	type SentimentCanaryVerdict,
	sentimentCanaryBodyDigest,
	sentimentCanaryContractSchema,
	sentimentCanaryInputDigests,
} from "./canary";
export {
	ASPECT_LOCAL_VALIDATION_CODES,
	type AspectLocalValidationCode,
	assessCandidate,
	buildValidationContext,
	type CandidateAssessment,
	classifySentiment,
	countFilteredClaimCodes,
	type FilteredClaim,
	isAspectLocalValidationCode,
	SENTIMENT_MAX_OUTPUT_TOKENS,
	type SentimentClassification,
	type SentimentClassifierDeps,
	SentimentValidationError,
	sentimentInputHash,
	type UnresolvedTarget,
	type ValidatedAspect,
	type ValidatedClassification,
	type ValidatedEntitySentiment,
	type ValidationContext,
	validateClassification,
	validateClassificationDetailed,
	validateSentimentResult,
	validateSentimentResultDetailed,
} from "./classifier";
export {
	type ControlActor,
	consumePermitPhase,
	DISPATCH_CONTROL_KEY,
	type DispatchControlState,
	type DispatchState,
	expireUnconsumedPermits,
	findLivePermit,
	type IssuePermitArgs,
	isHeld,
	isPermitEffective,
	isResumeRepairBudget,
	isResumeVerifyBudget,
	issuePermit,
	type ListedPermit,
	listControlEvents,
	listPermits,
	loadPermit,
	lockedLifecyclePermits,
	PERMIT_ESTIMATED_BUDGET_MAX_USD,
	PERMIT_LIVE_STATES,
	PERMIT_PHASES,
	PERMIT_PURPOSES,
	PermitConflictError,
	type PermitPhase,
	type PermitPurpose,
	type PermitSettlement,
	type PhaseBudget,
	permitPurposeAllowsPhase,
	permitSettlementFor,
	RESERVATION_ESTIMATES_USD,
	RESUME_REPAIR_PHASE_BUDGET,
	RESUME_VERIFY_PHASE_BUDGET,
	readDispatchState,
	requireActor,
	revokePermit,
	settlePermitReservation,
	transitionDispatch,
} from "./controls";
export {
	brandEntity,
	competitorEntity,
	containsBoundedTerm,
	type DetectableEntity,
	type DetectedMention,
	detectEntityMentions,
	entityTerms,
	mentionTerms,
	normalizeDomainTerm,
} from "./detector";
export {
	DIAGNOSTIC_MAX_BYTES,
	DIAGNOSTIC_REASONS,
	DIAGNOSTIC_STAGES,
	type DiagnosticReason,
	type DiagnosticStage,
	diagnostic,
	isValidationCode,
	type SentimentDiagnostic,
	safeGenerationId,
	sentimentDiagnosticSchema,
	serializeDiagnostic,
} from "./diagnostics";
export {
	enqueueSentimentBestEffort,
	type SentimentEnqueueOutcome,
	type SentimentSender,
	sendSentimentJob,
} from "./enqueue";
export {
	ClaimLostError,
	type SafeSentimentError,
	SentimentJobError,
	safeErrorMessage,
	sanitizeSentimentError,
} from "./errors";
export type { PaidResponseEnvelope } from "./errors-validation";
export {
	REQUEST_PROFILE_VERSION,
	type RequestProfile,
	requestScopeKey,
	SCHEMA_FINGERPRINT_VERSION,
	schemaShapeFingerprint,
	sentimentRequestProfile,
} from "./fingerprint";
export {
	type AnchorContext,
	type AnchorGrounding,
	belongsOnlyToOthers,
	type GroundingMap,
	groundAnchors,
	isAttributable,
	namesOnlyOthers,
} from "./grounding";
export { type HeldReleaseResult, type HeldWorkItem, listHeldWork, releaseHeldWork } from "./held-release";
export {
	type DispatchContext,
	type DispatchDeps,
	enqueueResumableSentimentRuns,
	listResumableSentimentRuns,
	permitAllowsRepair,
	permitAllowsVerify,
	RESUME_BATCH_MAX,
	type ResumableEnqueueResult,
	type ResumableSentimentRun,
	resumableEvidence,
	runSentimentJob,
	SentimentDispatchHeldError,
	type SentimentJobDeps,
	type SentimentJobOptions,
	type SentimentJobOutcome,
} from "./job";
export {
	bucketForRange,
	categoryLabel,
	compareObservationsAscending,
	computeEntityMetrics,
	type EntityCounts,
	type EntityMetrics,
	extremesAllocation,
	LOW_SAMPLE_THRESHOLD,
	type RosterCandidate,
	type ScoredObservation,
	SENTIMENT_SORT_KEYS,
	type SentimentBucket,
	type SentimentSortKey,
	type SentimentView,
	type SortableEntityRow,
	selectChartRoster,
	sortEntityRows,
	splitExtremes,
	viewVisibility,
} from "./metrics";
export {
	buildSentimentPrompt,
	renderAnchoredAnswer,
	SENTIMENT_EVIDENCE_RULES,
	SENTIMENT_KEY_RULES,
	SENTIMENT_SCORE_RULES,
} from "./prompt";
export { resolveSentimentProvider, SentimentProviderError } from "./provider";
export { ensureSentimentQueue, SENTIMENT_QUEUE_OPTIONS, type SentimentQueueAdmin } from "./queue-setup";
export {
	type AnalyzableText,
	analyzableText,
	analyzeAnswerRanges,
	type ExcludedRange,
	type ExcludedRangeKind,
	hasNaturalContent,
	isExcludedOffset,
	naturalSlices,
	naturalTextOf,
	type TextRange,
} from "./ranges";
export {
	type SentimentRunCoverageStatus,
	selectedSentimentAnalyses,
	selectedSentimentAnalysisIds,
	sentimentRunCoverageStatus,
} from "./read-selection";
export {
	planReanchor,
	type ReanchorAction,
	type ReanchorPlan,
	type SpanMapping,
	type StoredEntityResult,
	type StoredTargetResult,
} from "./reanchor";
export {
	applyReanchorEntry,
	buildReanchorManifest,
	manifestDigest as reanchorManifestDigest,
	planAnalysis as planReanchorAnalysis,
	REANCHOR_MANIFEST_VERSION,
	type ReanchorApplyOutcome,
	type ReanchorManifest,
	type ReanchorManifestEntry,
	type ReanchorScope,
	reanchorStatus,
} from "./reanchor-apply";
export {
	backoffMs,
	buildRepairPrompt,
	buildVerifierPrompt,
	HUMAN_ADJUDICATION_VERSION,
	mergeRepairedEntities,
	RESOLUTION_CASE_STATUSES,
	RESOLUTION_POLICY,
	REVIEW_REASONS,
	type ResolutionCaseStatus,
	type ResolutionPolicy,
	type ReviewReason,
	repairResultSchemaFor,
	SENTIMENT_VERIFIER_VERSION,
	VERIFIER_ISSUE_CODES,
	type VerifierIssue,
	type VerifierIssueCode,
	type VerifierResult,
	verifierIssuesToTargets,
	verifierResultSchemaFor,
} from "./resolution";
export {
	applyResumeForVerify,
	CALL_LIMIT_RESUMABLE_PATH,
	manifestSha256,
	RESUME_DEFAULT_BATCH,
	RESUME_MANIFEST_VERSION,
	RESUME_REVIEW_REASONS,
	RESUME_VERIFY_ESTIMATED_BUDGET_USD,
	RESUME_VERIFY_TTL_SECONDS,
	type ResumeApplyResult,
	type ResumeApplySkip,
	type ResumeEligible,
	type ResumeExclusion,
	type ResumeManifest,
	type ResumeReviewReason,
	resumePermitFor,
	selectCallLimitCandidate,
	selectResumableForVerify,
	selectResumeCandidate,
	selectStoredCandidate,
	selectVerifierRejectedCandidate,
} from "./resume";
export {
	assertProviderSchemaBudget,
	dereferenceSchema,
	measureSchemaBudget,
	PROVIDER_SCHEMA_LIMITS,
	type SchemaBudget,
	type SchemaBudgetViolation,
	schemaBudgetViolations,
} from "./schema-budget";
export {
	applyVerifierFilteredSettlements,
	type SettleCandidate,
	type SettleExclusion,
	type SettleManifest,
	type SettleResult,
	selectVerifierFilteredSettlements,
} from "./settle";
export {
	type AnalysisClaim,
	type ClaimOptions,
	type ClaimOutcome,
	candidatesFromMentions,
	chargeResolutionCase,
	claimAnalysis,
	type DetectionResult,
	detectionResultFor,
	type Executor,
	ensureAnalysis,
	ensureResolutionCase,
	finishProviderAttempt,
	isAnalysisCurrent,
	isAnalysisTerminallyFailed,
	listUnresolvedCases,
	loadAnalysisState,
	loadDetectableEntities,
	loadDetection,
	loadMentions,
	loadProviderAttempts,
	loadResolutionCase,
	loadRunForSentiment,
	markAnalysis,
	openProviderAttempt,
	persistClassification,
	persistDetection,
	persistMentions,
	type ResolutionOwner,
	recordSentimentUsageEvent,
	runInTransaction,
	type StoredAnalysisState,
	type StoredMention,
	type StoredResolutionCase,
	type StoredRunForSentiment,
	type UnresolvedCaseRow,
	updateResolutionCase,
} from "./store";
export { extractAnswerBody, type IndexedText, normalizeIndexed, normalizeText } from "./text";
export {
	assertStrictStructuredOutputSubset,
	BRAND_ENTITY_KEY,
	compareSentimentEntities,
	EVIDENCE_MAX_ITEMS,
	EVIDENCE_POLARITIES,
	EVIDENCE_QUOTE_MAX_LENGTH,
	type EvidencePolarity,
	isScoreCategoryConsistent,
	SENTIMENT_ASPECT_KEYS,
	SENTIMENT_ASPECTS,
	SENTIMENT_CATEGORIES,
	SENTIMENT_CLAIM_TIMEOUT_SECONDS,
	SENTIMENT_CLASSIFIER_VERSION,
	SENTIMENT_DETECTION_STATUSES,
	SENTIMENT_DETECTOR_VERSION,
	SENTIMENT_MODEL,
	SENTIMENT_PROVIDER_ID,
	SENTIMENT_QUEUE,
	SENTIMENT_READABLE_CLASSIFIER_VERSIONS,
	SENTIMENT_SCHEMA_DEFINITIONS,
	SENTIMENT_TAXONOMY_VERSION,
	type SentimentAnalysisStatus,
	type SentimentAspectKey,
	type SentimentCandidate,
	type SentimentCategory,
	type SentimentClassificationResult,
	type SentimentDetectionStatus,
	type SentimentEvidence,
	type SentimentEvidenceRef,
	type SentimentJobData,
	type SentimentProviderAspect,
	type SentimentProviderEntity,
	type SentimentProviderResult,
	STRICT_STRUCTURED_OUTPUT_KEYWORDS,
	sentimentClassificationResultSchema,
	sentimentJobSchema,
	sentimentProviderResultSchema,
	sentimentProviderResultSchemaFor,
	sentimentSingletonKey,
	sortSentimentEntities,
	toClassificationResult,
	toProviderResult,
} from "./types";
