export {
	decodeRunCursor,
	encodeRunCursor,
	type MentionBackfillCounts,
	type MentionBackfillResult,
	type RunCursor,
	runMentionBackfill,
	runSentimentEnqueue,
	type SentimentEnqueueInventory,
	type SentimentEnqueueResult,
} from "./backfill";
export {
	classifySentiment,
	locateEvidence,
	type SentimentClassification,
	type SentimentClassifierDeps,
	SentimentValidationError,
	sentimentInputHash,
	type ValidatedAspect,
	type ValidatedEntitySentiment,
	validateSentimentResult,
} from "./classifier";
export {
	brandEntity,
	competitorEntity,
	containsBoundedTerm,
	type DetectableEntity,
	type DetectedMention,
	detectEntityMentions,
	entityTerms,
	normalizeDomainTerm,
} from "./detector";
export {
	enqueueSentimentBestEffort,
	type SentimentEnqueueOutcome,
	type SentimentSender,
	sendSentimentJob,
} from "./enqueue";
export {
	ClaimLostError,
	type SafeSentimentError,
	SentimentJobError,
	safeErrorMessage,
	sanitizeSentimentError,
} from "./errors";
export { runSentimentJob, type SentimentJobDeps, type SentimentJobOptions, type SentimentJobOutcome } from "./job";
export {
	bucketForRange,
	categoryLabel,
	compareObservationsAscending,
	computeEntityMetrics,
	type EntityCounts,
	type EntityMetrics,
	extremesAllocation,
	LOW_SAMPLE_THRESHOLD,
	type RosterCandidate,
	type ScoredObservation,
	SENTIMENT_SORT_KEYS,
	type SentimentBucket,
	type SentimentSortKey,
	type SentimentView,
	type SortableEntityRow,
	selectChartRoster,
	sortEntityRows,
	splitExtremes,
	viewVisibility,
} from "./metrics";
export { buildSentimentPrompt, SENTIMENT_EVIDENCE_RULES, SENTIMENT_SCORE_RULES } from "./prompt";
export { resolveSentimentProvider, SentimentProviderError } from "./provider";
export { ensureSentimentQueue, SENTIMENT_QUEUE_OPTIONS, type SentimentQueueAdmin } from "./queue-setup";
export {
	type AnalysisClaim,
	type ClaimOutcome,
	candidatesFromMentions,
	claimAnalysis,
	type DetectionResult,
	detectionResultFor,
	ensureAnalysis,
	isAnalysisCurrent,
	loadDetectableEntities,
	loadDetection,
	loadMentions,
	loadRunForSentiment,
	markAnalysis,
	persistClassification,
	persistDetection,
	persistMentions,
	type StoredMention,
	type StoredRunForSentiment,
} from "./store";
export { extractAnswerBody, type IndexedText, normalizeIndexed, normalizeText } from "./text";
export {
	BRAND_ENTITY_KEY,
	EVIDENCE_MAX_ITEMS,
	EVIDENCE_POLARITIES,
	EVIDENCE_QUOTE_MAX_LENGTH,
	type EvidencePolarity,
	isScoreCategoryConsistent,
	SENTIMENT_ASPECT_KEYS,
	SENTIMENT_ASPECTS,
	SENTIMENT_CATEGORIES,
	SENTIMENT_CLAIM_TIMEOUT_SECONDS,
	SENTIMENT_CLASSIFIER_VERSION,
	SENTIMENT_DETECTION_STATUSES,
	SENTIMENT_DETECTOR_VERSION,
	SENTIMENT_MODEL,
	SENTIMENT_PROVIDER_ID,
	SENTIMENT_QUEUE,
	SENTIMENT_TAXONOMY_VERSION,
	type SentimentAnalysisStatus,
	type SentimentAspectKey,
	type SentimentCandidate,
	type SentimentCategory,
	type SentimentClassificationResult,
	type SentimentDetectionStatus,
	type SentimentEvidence,
	type SentimentJobData,
	sentimentClassificationResultSchema,
	sentimentJobSchema,
	sentimentSingletonKey,
} from "./types";
