export {
	ANCHOR_MAX_COUNT,
	anchorMap,
	type EvidenceAnchor,
	isAnchorId,
	SENTIMENT_EVIDENCE_VERSION,
	segmentAnswer,
} from "./anchors";
export {
	decodeRunCursor,
	encodeRunCursor,
	type MentionBackfillCounts,
	type MentionBackfillResult,
	type RunCursor,
	runMentionBackfill,
	runSentimentEnqueue,
	type SentimentEnqueueInventory,
	type SentimentEnqueueResult,
} from "./backfill";
export {
	acceptCanaryRunId,
	evaluateSentimentCanary,
	inspectSentimentCanaryRun,
	inspectSentimentCanaryRunState,
	isPristineCanaryRun,
	parseSentimentCanaryContract,
	preflightSentimentCanary,
	runSentimentCanary,
	SENTIMENT_CANARY_DEADLINE_MS,
	SENTIMENT_CANARY_LIMITS,
	SENTIMENT_CANARY_REJECT_CODES,
	SENTIMENT_CANARY_WATCHDOG_MS,
	type SentimentCanaryContract,
	SentimentCanaryContractError,
	type SentimentCanaryEntity,
	SentimentCanaryError,
	SentimentCanaryInputDriftError,
	type SentimentCanaryOutcome,
	type SentimentCanaryReason,
	type SentimentCanaryRejectCode,
	type SentimentCanaryReport,
	type SentimentCanaryRunDescription,
	type SentimentCanaryRunState,
	type SentimentCanaryVerdict,
	sentimentCanaryBodyDigest,
	sentimentCanaryContractSchema,
	sentimentCanaryInputDigests,
} from "./canary";
export {
	classifySentiment,
	SENTIMENT_MAX_OUTPUT_TOKENS,
	type SentimentClassification,
	type SentimentClassifierDeps,
	SentimentValidationError,
	sentimentInputHash,
	type ValidatedAspect,
	type ValidatedEntitySentiment,
	validateClassification,
	validateSentimentResult,
} from "./classifier";
export {
	type AnchorContext,
	type AnchorGrounding,
	type GroundingMap,
	groundAnchors,
	isAttributable,
	namesOnlyOthers,
} from "./grounding";
export {
	brandEntity,
	competitorEntity,
	containsBoundedTerm,
	type DetectableEntity,
	type DetectedMention,
	detectEntityMentions,
	entityTerms,
	mentionTerms,
	normalizeDomainTerm,
} from "./detector";
export {
	DIAGNOSTIC_MAX_BYTES,
	DIAGNOSTIC_REASONS,
	DIAGNOSTIC_STAGES,
	type DiagnosticReason,
	type DiagnosticStage,
	diagnostic,
	isValidationCode,
	type SentimentDiagnostic,
	safeGenerationId,
	sentimentDiagnosticSchema,
	serializeDiagnostic,
} from "./diagnostics";
export {
	enqueueSentimentBestEffort,
	type SentimentEnqueueOutcome,
	type SentimentSender,
	sendSentimentJob,
} from "./enqueue";
export {
	ClaimLostError,
	type SafeSentimentError,
	SentimentJobError,
	safeErrorMessage,
	sanitizeSentimentError,
} from "./errors";
export type { PaidResponseEnvelope } from "./errors-validation";
export { runSentimentJob, type SentimentJobDeps, type SentimentJobOptions, type SentimentJobOutcome } from "./job";
export {
	bucketForRange,
	categoryLabel,
	compareObservationsAscending,
	computeEntityMetrics,
	type EntityCounts,
	type EntityMetrics,
	extremesAllocation,
	LOW_SAMPLE_THRESHOLD,
	type RosterCandidate,
	type ScoredObservation,
	SENTIMENT_SORT_KEYS,
	type SentimentBucket,
	type SentimentSortKey,
	type SentimentView,
	type SortableEntityRow,
	selectChartRoster,
	sortEntityRows,
	splitExtremes,
	viewVisibility,
} from "./metrics";
export {
	buildSentimentPrompt,
	renderAnchoredAnswer,
	SENTIMENT_EVIDENCE_RULES,
	SENTIMENT_KEY_RULES,
	SENTIMENT_SCORE_RULES,
} from "./prompt";
export { resolveSentimentProvider, SentimentProviderError } from "./provider";
export { ensureSentimentQueue, SENTIMENT_QUEUE_OPTIONS, type SentimentQueueAdmin } from "./queue-setup";
export {
	type AnalyzableText,
	analyzableText,
	analyzeAnswerRanges,
	type ExcludedRange,
	type ExcludedRangeKind,
	hasNaturalContent,
	isExcludedOffset,
	naturalSlices,
	naturalTextOf,
	type TextRange,
} from "./ranges";
export {
	type AnalysisClaim,
	type ClaimOptions,
	type ClaimOutcome,
	candidatesFromMentions,
	claimAnalysis,
	type DetectionResult,
	detectionResultFor,
	ensureAnalysis,
	isAnalysisCurrent,
	isAnalysisTerminallyFailed,
	loadAnalysisState,
	loadDetectableEntities,
	loadDetection,
	loadMentions,
	loadRunForSentiment,
	markAnalysis,
	persistClassification,
	persistDetection,
	persistMentions,
	type StoredAnalysisState,
	type StoredMention,
	type StoredRunForSentiment,
} from "./store";
export { extractAnswerBody, type IndexedText, normalizeIndexed, normalizeText } from "./text";
export {
	BRAND_ENTITY_KEY,
	compareSentimentEntities,
	EVIDENCE_MAX_ITEMS,
	EVIDENCE_POLARITIES,
	EVIDENCE_QUOTE_MAX_LENGTH,
	type EvidencePolarity,
	isScoreCategoryConsistent,
	SENTIMENT_ASPECT_KEYS,
	SENTIMENT_ASPECTS,
	SENTIMENT_CATEGORIES,
	SENTIMENT_CLAIM_TIMEOUT_SECONDS,
	SENTIMENT_CLASSIFIER_VERSION,
	SENTIMENT_DETECTION_STATUSES,
	SENTIMENT_DETECTOR_VERSION,
	SENTIMENT_MODEL,
	SENTIMENT_PROVIDER_ID,
	SENTIMENT_QUEUE,
	SENTIMENT_TAXONOMY_VERSION,
	type SentimentAnalysisStatus,
	type SentimentAspectKey,
	type SentimentCandidate,
	type SentimentCategory,
	type SentimentClassificationResult,
	type SentimentDetectionStatus,
	type SentimentEvidence,
	type SentimentEvidenceRef,
	type SentimentJobData,
	SENTIMENT_READABLE_CLASSIFIER_VERSIONS,
	STRICT_STRUCTURED_OUTPUT_KEYWORDS,
	type SentimentProviderAspect,
	type SentimentProviderEntity,
	type SentimentProviderResult,
	assertStrictStructuredOutputSubset,
	sentimentClassificationResultSchema,
	sentimentJobSchema,
	sentimentProviderResultSchema,
	sentimentProviderResultSchemaFor,
	toClassificationResult,
	toProviderResult,
	sentimentSingletonKey,
	sortSentimentEntities,
} from "./types";
